version: 2

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - node_modules

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt
    - goimports

formatters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/gorbit/orbitalrush

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

